version: '3.9'

services:
  nginx:
    container_name: nginx-lb
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"       
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - evol.api1
      - evol.api2
      - evol.api3
#      - evol.client
    networks:
      - evol-network
    restart: unless-stopped

  evol.api1:
    container_name: evol.api1
    build:
      context: ./src/eVOL.Api
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - evol.mysql
      - evol.redis
      - evol.mongodb
      - evol.seq
    networks:
      - evol-network
    expose:
      - "8080"
    environment:
      - DOTNET_URLS=http://0.0.0.0:8080
    restart: unless-stopped

  evol.api2:
    container_name: evol.api2
    build:
      context: ./src/eVOL.Api
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - evol.mysql
      - evol.redis
      - evol.mongodb
      - evol.seq
    networks:
      - evol-network
    expose:
      - "8080"
    environment:
      - DOTNET_URLS=http://0.0.0.0:8080
    restart: unless-stopped

  evol.api3:
    container_name: evol.api3
    build:
      context: ./src/eVOL.Api
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - evol.mysql
      - evol.redis
      - evol.mongodb
      - evol.seq
    networks:
      - evol-network
    expose:
      - "8080"
    environment:
      - DOTNET_URLS=http://0.0.0.0:8080
    restart: unless-stopped
    ports:
      - "8083:8080"

#  evol.client:
#    container_name: evol.client
#    build:
#      context: ./src/eVOL.Client/eVOL.Client
#      dockerfile: Dockerfile
#    ports:
#      - "5001:8080"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#   depends_on:
#      - evol.api1
#      - evol.api2
#      - evol.api3
#    networks:
#      - evol-network
#    restart: unless-stopped

  evol.mysql:
    container_name: evol.mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: evol_db
      MYSQL_USER: evol_user
      MYSQL_PASSWORD: evol_password
    ports:
      - "3307:3306"
    volumes:
      - evol-mysql-data:/var/lib/mysql
    networks:
      - evol-network
    restart: unless-stopped

  evol.mongodb:
    container_name: evol.mongodb
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: evol_user
      MONGO_INITDB_ROOT_PASSWORD: evol_password
      MONGO_INITDB_DATABASE: evol_chat_db
    ports:
      - "27018:27017"
    volumes:
      - evol-mongodb-data:/data/db
    networks:
      - evol-network
    restart: unless-stopped

  evol.redis:
    container_name: evol.redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - evol-redis-data:/data
    networks:
      - evol-network
    restart: unless-stopped

  evol.seq:
    container_name: evol.seq
    image: datalust/seq:latest
    ports:
      - "5341:80"   
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=1234
    volumes:
      - evol-seq-data:/data
    networks:
      - evol-network
    restart: unless-stopped


volumes:
  evol-mysql-data:
  evol-mongodb-data:
  evol-redis-data:
  evol-seq-data:


networks:
  evol-network:
    driver: bridge
